### PR TITLE
Lunar Hotel: Connect Rooms And Reservations

### PR DESCRIPTION
**Pull request by DammyShittu**
## In this PR, I;

- wired up reservations redux to the reservations page,
- displayed corresponding sections on their respective pages,
- handled logic to calculate the number of reservation days and date validation.

### CODE REVIEW

**Review by mmatongo — APPROVED** [review]
Hi @DammyShittu

The project doesn't seem to be working.
Please make changes.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Review by mmatongo — CHANGES_REQUESTED** [review]
App does not allow users to create a reservation, please fix this.

**Comment by DammyShittu** [comment]
> App does not allow users to create a reservation, please fix this.

Some changes were made on the backend, you'll be able to create reservations once the changes on the backend have been merged.

**Review by medaminedev66 — APPROVED** [review]
Hi @DammyShittu , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

**Pull request merged**
